//==============================================================================
// Module: turbo_decoder_axi_lite
// Description:
//   AXI4-Lite register wrapper for the parallel LTE Turbo Decoder.
//
//   Intended Zybo/Zynq usage:
//     Package this module as a custom IP and connect S_AXI to the Zynq PS
//     M_AXI_GP0 port in a Vivado block design. The raw AXI signals are then
//     internal fabric nets; the board-level top is generated by Vivado.
//
// Register map, 32-bit word accesses:
//   0x00 CONTROL      W bit0=start pulse, bit1=clear done sticky
//   0x04 STATUS       R bit0=done sticky, bit1=busy, bit2=decode_done pulse
//   0x08 LOAD_ADDR    W input BRAM row address
//   0x0C LOAD_DATA    W bits[9:0] = {core1[4:0], core0[4:0]}
//   0x10 LOAD_SEL     W bits[2:0] select input BRAM
//                     0=sys_odd, 1=sys_even, 2=par1_odd, 3=par1_even,
//                     4=sys_ilv_odd, 5=sys_ilv_even, 6=par2_odd, 7=par2_even
//   0x14 LOAD_COMMIT  W any value pulses one input BRAM write
//   0x18 LD_RD_ADDR   W LD/extrinsic row read address
//   0x1C LD_EVEN      R bits[11:0] final copied extrinsic even row
//   0x20 LD_ODD       R bits[11:0] final copied extrinsic odd row
//   0x24 HARD_RD_ADDR W hard-decision row read address
//   0x28 HARD_BITS    R bits[3:0]:
//                       [0]=core0/even, [1]=core1/even,
//                       [2]=core0/odd,  [3]=core1/odd
//==============================================================================
module turbo_decoder_axi_lite #(
    parameter C_S_AXI_ADDR_WIDTH = 12,
    parameter C_S_AXI_DATA_WIDTH = 32,

    parameter K              = 3200,
    parameter NUM_SISO       = 2,
    parameter SEG_LEN        = K / NUM_SISO,
    parameter TAIL_LEN       = 3,
    parameter WIN_LEN        = 30,
    parameter PAPER_BOUNDARY = 1,
    parameter NUM_WINDOWS    = (SEG_LEN + TAIL_LEN + WIN_LEN - 1) / WIN_LEN,
    parameter ROW_DEPTH      = (SEG_LEN + 1) / 2,
    parameter INPUT_ROW_DEPTH = (SEG_LEN + TAIL_LEN + 1) / 2,
    parameter ROW_ADDR_W     = 10,
    parameter FRAME_ADDR_W   = 12,
    parameter PI_W           = 12,
    parameter INPUT_WORD_W   = 10,
    parameter EXTR_WORD_W    = 12,
    parameter QPP_LUT_FILE   = "data/qpp_3200.hex",
    parameter NUM_HALF_ITER  = 4'd11
) (
    input  wire                              s_axi_aclk,
    input  wire                              s_axi_aresetn,

    input  wire [C_S_AXI_ADDR_WIDTH-1:0]     s_axi_awaddr,
    input  wire                              s_axi_awvalid,
    output reg                               s_axi_awready,

    input  wire [C_S_AXI_DATA_WIDTH-1:0]     s_axi_wdata,
    input  wire [(C_S_AXI_DATA_WIDTH/8)-1:0] s_axi_wstrb,
    input  wire                              s_axi_wvalid,
    output reg                               s_axi_wready,

    output reg  [1:0]                        s_axi_bresp,
    output reg                               s_axi_bvalid,
    input  wire                              s_axi_bready,

    input  wire [C_S_AXI_ADDR_WIDTH-1:0]     s_axi_araddr,
    input  wire                              s_axi_arvalid,
    output reg                               s_axi_arready,

    output reg  [C_S_AXI_DATA_WIDTH-1:0]     s_axi_rdata,
    output reg  [1:0]                        s_axi_rresp,
    output reg                               s_axi_rvalid,
    input  wire                              s_axi_rready
);

    localparam [7:0] REG_CONTROL     = 8'h00;
    localparam [7:0] REG_STATUS      = 8'h04;
    localparam [7:0] REG_LOAD_ADDR   = 8'h08;
    localparam [7:0] REG_LOAD_DATA   = 8'h0C;
    localparam [7:0] REG_LOAD_SEL    = 8'h10;
    localparam [7:0] REG_LOAD_COMMIT = 8'h14;
    localparam [7:0] REG_LD_ADDR     = 8'h18;
    localparam [7:0] REG_LD_EVEN     = 8'h1C;
    localparam [7:0] REG_LD_ODD      = 8'h20;
    localparam [7:0] REG_HARD_ADDR   = 8'h24;
    localparam [7:0] REG_HARD_BITS   = 8'h28;

    reg [C_S_AXI_ADDR_WIDTH-1:0] awaddr_hold;
    reg [C_S_AXI_DATA_WIDTH-1:0] wdata_hold;
    reg [(C_S_AXI_DATA_WIDTH/8)-1:0] wstrb_hold;
    reg aw_seen;
    reg w_seen;

    wire aw_take = s_axi_awready && s_axi_awvalid;
    wire w_take  = s_axi_wready  && s_axi_wvalid;
    wire have_aw = aw_seen || aw_take;
    wire have_w  = w_seen  || w_take;
    wire [C_S_AXI_ADDR_WIDTH-1:0] write_addr = aw_take ? s_axi_awaddr : awaddr_hold;
    wire [C_S_AXI_DATA_WIDTH-1:0] write_data = w_take  ? s_axi_wdata  : wdata_hold;
    wire [(C_S_AXI_DATA_WIDTH/8)-1:0] write_strb = w_take ? s_axi_wstrb : wstrb_hold;
    wire write_has_strobe = |write_strb;

    reg                         start_pulse;
    reg                         load_pulse;
    reg [2:0]                   load_bram_sel_reg;
    reg [ROW_ADDR_W-1:0]        load_addr_reg;
    reg [INPUT_WORD_W-1:0]      load_data_reg;
    reg [ROW_ADDR_W-1:0]        ld_rd_addr_reg;
    reg [ROW_ADDR_W-1:0]        hard_rd_addr_reg;
    reg                         busy;
    reg                         done_sticky;

    wire                        core_decode_done;
    wire [EXTR_WORD_W-1:0]      ld_rd_data;
    wire [EXTR_WORD_W-1:0]      ld_rd_data_odd;
    wire [3:0]                  hard_rd_data;

    turbo_decoder #(
        .K(K),
        .NUM_SISO(NUM_SISO),
        .SEG_LEN(SEG_LEN),
        .TAIL_LEN(TAIL_LEN),
        .WIN_LEN(WIN_LEN),
        .PAPER_BOUNDARY(PAPER_BOUNDARY),
        .NUM_WINDOWS(NUM_WINDOWS),
        .ROW_DEPTH(ROW_DEPTH),
        .INPUT_ROW_DEPTH(INPUT_ROW_DEPTH),
        .ROW_ADDR_W(ROW_ADDR_W),
        .FRAME_ADDR_W(FRAME_ADDR_W),
        .PI_W(PI_W),
        .INPUT_WORD_W(INPUT_WORD_W),
        .EXTR_WORD_W(EXTR_WORD_W),
        .QPP_LUT_FILE(QPP_LUT_FILE),
        .NUM_HALF_ITER(NUM_HALF_ITER)
    ) u_decoder (
        .clk(s_axi_aclk),
        .rst_n(s_axi_aresetn),
        .start(start_pulse),
        .load_en(load_pulse),
        .load_bram_sel(load_bram_sel_reg),
        .load_addr(load_addr_reg),
        .load_data(load_data_reg),
        .decode_done(core_decode_done),
        .ld_rd_addr(ld_rd_addr_reg),
        .ld_rd_data(ld_rd_data),
        .ld_rd_data_odd(ld_rd_data_odd),
        .hard_rd_addr(hard_rd_addr_reg),
        .hard_rd_data(hard_rd_data)
    );

    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            s_axi_awready <= 1'b0;
            s_axi_wready  <= 1'b0;
            s_axi_bresp   <= 2'b00;
            s_axi_bvalid  <= 1'b0;
            awaddr_hold   <= {C_S_AXI_ADDR_WIDTH{1'b0}};
            wdata_hold    <= {C_S_AXI_DATA_WIDTH{1'b0}};
            wstrb_hold    <= {(C_S_AXI_DATA_WIDTH/8){1'b0}};
            aw_seen       <= 1'b0;
            w_seen        <= 1'b0;

            start_pulse       <= 1'b0;
            load_pulse        <= 1'b0;
            load_bram_sel_reg <= 3'd0;
            load_addr_reg     <= {ROW_ADDR_W{1'b0}};
            load_data_reg     <= {INPUT_WORD_W{1'b0}};
            ld_rd_addr_reg    <= {ROW_ADDR_W{1'b0}};
            hard_rd_addr_reg  <= {ROW_ADDR_W{1'b0}};
            busy              <= 1'b0;
            done_sticky       <= 1'b0;
        end else begin
            if (aw_take)
                s_axi_awready <= 1'b0;
            else
                s_axi_awready <= !aw_seen && !s_axi_bvalid;

            if (w_take)
                s_axi_wready <= 1'b0;
            else
                s_axi_wready <= !w_seen && !s_axi_bvalid;
            start_pulse   <= 1'b0;
            load_pulse    <= 1'b0;

            if (aw_take) begin
                awaddr_hold <= s_axi_awaddr;
                aw_seen     <= 1'b1;
            end

            if (w_take) begin
                wdata_hold <= s_axi_wdata;
                wstrb_hold <= s_axi_wstrb;
                w_seen     <= 1'b1;
            end

            if (core_decode_done) begin
                busy        <= 1'b0;
                done_sticky <= 1'b1;
            end

            if (have_aw && have_w && !s_axi_bvalid) begin
                aw_seen      <= 1'b0;
                w_seen       <= 1'b0;
                s_axi_bresp  <= 2'b00;
                s_axi_bvalid <= 1'b1;

                if (write_has_strobe) begin
                    case (write_addr[7:0])
                        REG_CONTROL: begin
                            if (write_data[0] && !busy) begin
                                start_pulse <= 1'b1;
                                busy        <= 1'b1;
                                done_sticky <= 1'b0;
                            end
                            if (write_data[1])
                                done_sticky <= 1'b0;
                        end
                        REG_LOAD_ADDR: begin
                            load_addr_reg <= write_data[ROW_ADDR_W-1:0];
                        end
                        REG_LOAD_DATA: begin
                            load_data_reg <= write_data[INPUT_WORD_W-1:0];
                        end
                        REG_LOAD_SEL: begin
                            load_bram_sel_reg <= write_data[2:0];
                        end
                        REG_LOAD_COMMIT: begin
                            if (!busy)
                                load_pulse <= 1'b1;
                        end
                        REG_LD_ADDR: begin
                            ld_rd_addr_reg <= write_data[ROW_ADDR_W-1:0];
                        end
                        REG_HARD_ADDR: begin
                            hard_rd_addr_reg <= write_data[ROW_ADDR_W-1:0];
                        end
                        default: begin
                        end
                    endcase
                end
            end else if (s_axi_bvalid && s_axi_bready) begin
                s_axi_bvalid <= 1'b0;
            end
        end
    end

    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            s_axi_arready <= 1'b0;
            s_axi_rdata   <= {C_S_AXI_DATA_WIDTH{1'b0}};
            s_axi_rresp   <= 2'b00;
            s_axi_rvalid  <= 1'b0;
        end else begin
            s_axi_arready <= !s_axi_rvalid;

            if (s_axi_arready && s_axi_arvalid) begin
                s_axi_arready <= 1'b0;
                s_axi_rresp   <= 2'b00;
                s_axi_rvalid  <= 1'b1;

                case (s_axi_araddr[7:0])
                    REG_CONTROL:
                        s_axi_rdata <= {C_S_AXI_DATA_WIDTH{1'b0}};
                    REG_STATUS:
                        s_axi_rdata <= {{(C_S_AXI_DATA_WIDTH-3){1'b0}},
                                        core_decode_done, busy, done_sticky};
                    REG_LOAD_ADDR:
                        s_axi_rdata <= {{(C_S_AXI_DATA_WIDTH-ROW_ADDR_W){1'b0}},
                                        load_addr_reg};
                    REG_LOAD_DATA:
                        s_axi_rdata <= {{(C_S_AXI_DATA_WIDTH-INPUT_WORD_W){1'b0}},
                                        load_data_reg};
                    REG_LOAD_SEL:
                        s_axi_rdata <= {{(C_S_AXI_DATA_WIDTH-3){1'b0}},
                                        load_bram_sel_reg};
                    REG_LD_ADDR:
                        s_axi_rdata <= {{(C_S_AXI_DATA_WIDTH-ROW_ADDR_W){1'b0}},
                                        ld_rd_addr_reg};
                    REG_LD_EVEN:
                        s_axi_rdata <= {{(C_S_AXI_DATA_WIDTH-EXTR_WORD_W){1'b0}},
                                        ld_rd_data};
                    REG_LD_ODD:
                        s_axi_rdata <= {{(C_S_AXI_DATA_WIDTH-EXTR_WORD_W){1'b0}},
                                        ld_rd_data_odd};
                    REG_HARD_ADDR:
                        s_axi_rdata <= {{(C_S_AXI_DATA_WIDTH-ROW_ADDR_W){1'b0}},
                                        hard_rd_addr_reg};
                    REG_HARD_BITS:
                        s_axi_rdata <= {{(C_S_AXI_DATA_WIDTH-4){1'b0}},
                                        hard_rd_data};
                    default:
                        s_axi_rdata <= {C_S_AXI_DATA_WIDTH{1'b0}};
                endcase
            end else if (s_axi_rvalid && s_axi_rready) begin
                s_axi_rvalid <= 1'b0;
            end
        end
    end

endmodule
