#!/usr/bin/env python3
"""Generate the Vitis C header used by the Zybo turbo-decoder bring-up app."""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
from typing import Iterable


K = 3200
SEG_LEN = 1600
INPUT_ROW_DEPTH = 802
ROW_DEPTH = 800

INPUT_FILES = [
    ("sys_odd", "sys_odd_ram.hex"),
    ("sys_even", "sys_even_ram.hex"),
    ("par1_odd", "par1_odd_ram.hex"),
    ("par1_even", "par1_even_ram.hex"),
    ("sys_ilv_odd", "sys_ilv_odd_ram.hex"),
    ("sys_ilv_even", "sys_ilv_even_ram.hex"),
    ("par2_odd", "par2_odd_ram.hex"),
    ("par2_even", "par2_even_ram.hex"),
]


def parse_hex_words(path: Path, expected_count: int) -> list[int]:
    values: list[int] = []
    for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        text = line.split("#", 1)[0].strip()
        if not text:
            continue
        value = int(text, 16)
        if value < 0 or value > 0x3FF:
            raise ValueError(f"{path}:{line_no}: value 0x{value:x} does not fit in 10 bits")
        values.append(value)

    if len(values) != expected_count:
        raise ValueError(f"{path}: expected {expected_count} rows, found {len(values)}")
    return values


def parse_bits(path: Path, expected_count: int) -> list[int]:
    values: list[int] = []
    for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        text = line.split("#", 1)[0].strip()
        if not text:
            continue
        value = int(text, 10)
        if value not in (0, 1):
            raise ValueError(f"{path}:{line_no}: bit value must be 0 or 1, got {value}")
        values.append(value)

    if len(values) != expected_count:
        raise ValueError(f"{path}: expected {expected_count} bits, found {len(values)}")
    return values


def parse_metadata(path: Path) -> dict[str, str]:
    metadata: dict[str, str] = {}
    if not path.exists():
        return metadata
    for line in path.read_text(encoding="utf-8").splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        metadata[key.strip()] = value.strip()
    return metadata


def chunks(values: Iterable[int], size: int) -> Iterable[list[int]]:
    row: list[int] = []
    for value in values:
        row.append(value)
        if len(row) == size:
            yield row
            row = []
    if row:
        yield row


def format_word_array(values: list[int], hex_words: bool) -> str:
    lines: list[str] = []
    for row in chunks(values, 12 if hex_words else 32):
        if hex_words:
            text = ", ".join(f"0x{value:03x}" for value in row)
        else:
            text = ", ".join(str(value) for value in row)
        lines.append(f"        {text}")
    return ",\n".join(lines)


def generate_header(data_dir: Path, output: Path) -> None:
    metadata = parse_metadata(data_dir / "vector_metadata.txt")
    input_rows = [
        (name, parse_hex_words(data_dir / filename, INPUT_ROW_DEPTH))
        for name, filename in INPUT_FILES
    ]
    true_bits = parse_bits(data_dir / "true_info_bits.txt", K)
    rtl_hard_bits = parse_bits(data_dir / "rtl_final_hard_bits.txt", K)

    output.parent.mkdir(parents=True, exist_ok=True)
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    with output.open("w", encoding="utf-8", newline="\n") as f:
        f.write("/* Auto-generated by fpga_bringup/scripts/generate_vitis_vectors.py.\n")
        f.write(" * Do not edit this file by hand; regenerate it from the repo data directory.\n")
        f.write(f" * Generated: {generated_at}\n")
        if metadata:
            f.write(" * Vector metadata:")
            for key in ("K", "NUM_SISO", "SEG_LEN", "EBN0_DB", "CODE_RATE", "SEED", "TAIL_LEN"):
                if key in metadata:
                    f.write(f" {key}={metadata[key]}")
            f.write("\n")
        f.write(" */\n\n")
        f.write("#ifndef TURBO_TEST_VECTORS_H\n")
        f.write("#define TURBO_TEST_VECTORS_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define TURBO_VEC_K {K}U\n")
        f.write(f"#define TURBO_VEC_SEG_LEN {SEG_LEN}U\n")
        f.write(f"#define TURBO_VEC_INPUT_ROW_DEPTH {INPUT_ROW_DEPTH}U\n")
        f.write(f"#define TURBO_VEC_ROW_DEPTH {ROW_DEPTH}U\n")
        f.write("#define TURBO_VEC_NUM_INPUT_BRAMS 8U\n\n")

        f.write("static const char *const turbo_input_bram_names[TURBO_VEC_NUM_INPUT_BRAMS] = {\n")
        for index, (name, _) in enumerate(input_rows):
            comma = "," if index + 1 < len(input_rows) else ""
            f.write(f'    "{name}"{comma}\n')
        f.write("};\n\n")

        f.write("static const uint16_t turbo_input_bram[TURBO_VEC_NUM_INPUT_BRAMS][TURBO_VEC_INPUT_ROW_DEPTH] = {\n")
        for index, (name, values) in enumerate(input_rows):
            comma = "," if index + 1 < len(input_rows) else ""
            f.write(f"    /* {index}: {name} */\n")
            f.write("    {\n")
            f.write(format_word_array(values, hex_words=True))
            f.write(f"\n    }}{comma}\n")
        f.write("};\n\n")

        f.write("static const uint8_t turbo_true_info_bits[TURBO_VEC_K] = {\n")
        f.write(format_word_array(true_bits, hex_words=False))
        f.write("\n};\n\n")

        f.write("static const uint8_t turbo_rtl_expected_hard_bits[TURBO_VEC_K] = {\n")
        f.write(format_word_array(rtl_hard_bits, hex_words=False))
        f.write("\n};\n\n")

        f.write("#endif\n")

    print(f"Generated {output}")
    print(f"Input memories: {len(input_rows)} x {INPUT_ROW_DEPTH} rows")
    print(f"Truth bits: {len(true_bits)}")
    print(f"RTL expected hard bits: {len(rtl_hard_bits)}")


def main() -> int:
    repo_root = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, default=repo_root / "data",
                        help="Directory containing sys/parity BRAM hex files and truth bits")
    parser.add_argument("--output", type=Path,
                        default=repo_root / "fpga_bringup" / "vitis_app_src" / "turbo_test_vectors.h",
                        help="Output C header path")
    args = parser.parse_args()

    generate_header(args.data_dir.resolve(), args.output.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
