#!/usr/bin/env python3
"""
BER Calculator for LTE Turbo Decoder RTL vs Reference

Compares hard-bit decisions from:
  - Reference: ref_extrinsic.hex (golden model output, single SISO, 3072 bits)
  - RTL:       ld_ram_output.hex (full decoder output, 2 SISOs, 6144 bits folded)

Data formats:
  ref_extrinsic.hex: "ADDR: EXTR_ODD EXTR_EVEN"  (6-bit 2's complement each)
    - 1536 lines, 2 values per line => 3072 values
    - Generated by generate_test_data.py using a SINGLE SISO golden model
    - Indices 0..3071 correspond to one core's subframe

  ld_ram_output.hex: "EVEN_12b ODD_12b"  (per row)
    - 1536 rows
    - EVEN_12b = {col1_even[5:0], col0_even[5:0]}  col0=core0, col1=core1
    - ODD_12b  = {col1_odd[5:0],  col0_odd[5:0]}

  The RTL decoder has 2 parallel SISO cores:
    - Core 0 (CORE_ID=0): processes original bits 0..3071
    - Core 1 (CORE_ID=1): processes original bits 3072..6143

  Since the reference model only generated data for ONE SISO (3072 bits),
  we compare against Core 0's output (col0 from the LD BRAMs).

Hard-bit decision: sign of 6-bit signed extrinsic LLR
  - Positive (or zero) => decoded bit 0
  - Negative           => decoded bit 1
"""

import sys
import os

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'data')

def sign_extend_6bit(val):
    """Convert unsigned 6-bit to signed."""
    if val >= 32:
        return val - 64
    return val

def hard_decision(signed_val):
    """Hard bit: 0 if LLR >= 0, 1 if LLR < 0."""
    return 1 if signed_val < 0 else 0

def load_reference(filepath):
    """
    Load ref_extrinsic.hex: "ADDR: EXTR_ODD EXTR_EVEN"
    Returns list of 3072 signed extrinsic values in linear order.
    
    The generator writes pairs (i, i+1) where:
      e_odd  = extr_golden[i]   (despite the name, this is the FIRST of the pair)
      e_even = extr_golden[i+1] (this is the SECOND of the pair)
    """
    values = [0] * 3072
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            # Format: "ADDR: ODD EVEN"
            parts = line.split(":")
            if len(parts) != 2:
                continue
            addr = int(parts[0], 16)
            vals = parts[1].strip().split()
            if len(vals) != 2:
                continue
            # e_odd = extr_golden[addr], e_even = extr_golden[addr+1]
            e_first  = sign_extend_6bit(int(vals[0], 16))
            e_second = sign_extend_6bit(int(vals[1], 16))
            if addr < 3072:
                values[addr]     = e_first
            if addr + 1 < 3072:
                values[addr + 1] = e_second
    return values

def load_ld_output(filepath):
    """
    Load ld_ram_output.hex: "EVEN_HEX ODD_HEX"
    
    Each row r (0..1535):
      EVEN_HEX (12-bit): {col1_even[5:0], col0_even[5:0]}
      ODD_HEX  (12-bit): {col1_odd[5:0],  col0_odd[5:0]}
    
    Core 0 values at linear addresses:
      Row r => col0_even = extrinsic at address 2r
              col0_odd  = extrinsic at address 2r+1
    
    Returns: (core0_values[0..3071], core1_values[0..3071])
    """
    core0 = [0] * 3072
    core1 = [0] * 3072
    
    with open(filepath, 'r') as f:
        for row, line in enumerate(f):
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) != 2:
                print(f"WARNING: Unexpected format at row {row}: '{line}'")
                continue
            
            even_word = int(parts[0], 16)
            odd_word  = int(parts[1], 16)
            
            # Extract 6-bit fields
            col0_even = sign_extend_6bit(even_word & 0x3F)
            col1_even = sign_extend_6bit((even_word >> 6) & 0x3F)
            col0_odd  = sign_extend_6bit(odd_word & 0x3F)
            col1_odd  = sign_extend_6bit((odd_word >> 6) & 0x3F)
            
            addr_even = 2 * row       # linear address for even sample
            addr_odd  = 2 * row + 1   # linear address for odd sample
            
            if addr_even < 3072:
                core0[addr_even] = col0_even
                core1[addr_even] = col1_even
            if addr_odd < 3072:
                core0[addr_odd] = col0_odd
                core1[addr_odd] = col1_odd
    
    return core0, core1

def main():
    ref_path = os.path.join(DATA_DIR, 'ref_extrinsic.hex')
    ld_path  = os.path.join(DATA_DIR, 'ld_ram_output.hex')
    
    if not os.path.exists(ref_path):
        print(f"ERROR: Reference file not found: {ref_path}")
        sys.exit(1)
    if not os.path.exists(ld_path):
        print(f"ERROR: LD output file not found: {ld_path}")
        sys.exit(1)
    
    print("=" * 60)
    print("  LTE Turbo Decoder BER Calculator")
    print("=" * 60)
    
    # Load data
    ref_values = load_reference(ref_path)
    rtl_core0, rtl_core1 = load_ld_output(ld_path)
    
    print(f"\nReference: {len(ref_values)} extrinsic LLR values (single SISO)")
    print(f"RTL Core0: {len(rtl_core0)} values | RTL Core1: {len(rtl_core1)} values")
    
    # --- Hard-bit BER: Reference vs RTL Core 0 ---
    print("\n" + "-" * 60)
    print("  Hard-Bit BER: Reference (Golden) vs RTL Core 0")
    print("-" * 60)
    
    n_bits = len(ref_values)
    bit_errors = 0
    llr_mismatches = 0
    max_llr_diff = 0
    sum_llr_diff = 0
    
    # Show first few comparisons
    print(f"\n{'Addr':>5} | {'Ref LLR':>7} {'Ref Bit':>7} | {'RTL LLR':>7} {'RTL Bit':>7} | {'Match':>5}")
    print("-" * 60)
    
    for i in range(n_bits):
        ref_llr = ref_values[i]
        rtl_llr = rtl_core0[i]
        
        ref_bit = hard_decision(ref_llr)
        rtl_bit = hard_decision(rtl_llr)
        
        if ref_bit != rtl_bit:
            bit_errors += 1
        
        llr_diff = abs(ref_llr - rtl_llr)
        if llr_diff > 0:
            llr_mismatches += 1
        max_llr_diff = max(max_llr_diff, llr_diff)
        sum_llr_diff += llr_diff
        
        # Print first 20 and last 5
        if i < 20 or i >= n_bits - 5:
            match_str = "OK" if ref_bit == rtl_bit else "ERR"
            print(f"{i:5d} | {ref_llr:7d} {ref_bit:7d} | {rtl_llr:7d} {rtl_bit:7d} | {match_str:>5}")
        elif i == 20:
            print(f"  ... ({n_bits - 25} more rows) ...")
    
    ber = bit_errors / n_bits if n_bits > 0 else 0
    avg_llr_diff = sum_llr_diff / n_bits if n_bits > 0 else 0
    
    print("\n" + "=" * 60)
    print("  RESULTS")
    print("=" * 60)
    print(f"  Total bits compared:     {n_bits}")
    print(f"  Hard-bit errors:         {bit_errors}")
    print(f"  BER:                     {ber:.6f} ({ber*100:.4f}%)")
    print(f"  LLR value mismatches:    {llr_mismatches} / {n_bits}")
    print(f"  Max |LLR difference|:    {max_llr_diff}")
    print(f"  Avg |LLR difference|:    {avg_llr_diff:.2f}")
    print()
    
    if ber == 0:
        print("  *** PERFECT MATCH: Zero bit errors! ***")
    elif ber < 0.001:
        print("  *** EXCELLENT: BER < 0.1% — likely window-boundary quantization differences ***")
    elif ber < 0.01:
        print("  *** GOOD: BER < 1% — some deviations, check window boundaries ***")
    else:
        print("  *** WARNING: High BER — potential functional bug ***")
    
    if max_llr_diff <= 3:
        print("  Note: Small max LLR diff suggests RTL is functionally correct.")
        print("        Differences are expected from sliding-window vs full-frame BCJR.")
    
    # --- Distribution of bit errors ---
    if bit_errors > 0 and bit_errors <= 100:
        print(f"\n  Bit error locations (first {min(bit_errors, 50)}):")
        count = 0
        for i in range(n_bits):
            if hard_decision(ref_values[i]) != hard_decision(rtl_core0[i]):
                if count < 50:
                    print(f"    addr={i:4d}: ref_llr={ref_values[i]:3d} rtl_llr={rtl_core0[i]:3d}")
                count += 1
    
    print("\n" + "=" * 60)

if __name__ == "__main__":
    main()
